longterm_goals = [
    "Save for college",
    "Buy a house",
    "Start a business",
    "Travel the world",
    "Retire early",
    "Get married",
    "Have children",
    "Get a promotion",
    "Learn a new skill",
    "Write a book",
    "Learn to play an instrument",
    "Learn a new language",
    "Get in shape",
    "Run a marathon",
    "Start a family",
    "Get a pet",
    "Learn to cook",
    "Learn to dance",
    "Learn to code",
    "Learn to draw",
    "Learn to paint",
    "Learn to sing",
    "Learn to act",
    "Learn to write",
    "Learn to meditate",
    "Learn to garden",
    "Learn to swim",
    "Learn to surf",
    "Learn to ski",
    "Learn to snowboard",
    "Learn to skate",
    "Learn to skateboard",
    "Learn to play a sport",
    "Learn to play a game",
    "Learn to play a card game",
    "Go on a road trip",
    "Go on a hike",
    "Go on a camping trip",
    "Go on a vacation",
    "Go on a cruise",
    "Go on a safari",
    "Go on a retreat",
    "Go on a pilgrimage",
    "Go on a quest",
    "Go on a treasure hunt",
    "Go to a concert",
    "Go to a festival",
    "Go to a party",
    "Go to a wedding",
    "Go to a funeral",
    "Go to a graduation",
    "Go to a reunion",
    "Go to a meeting",
    "Go to a conference",
    "Go to a convention",
    "Get a degree",
    "Get a certification",
    "Get a license",
    "Get a permit",
    "Get a passport",
    "Get a visa",
    "Get a ticket",
    "Get a reservation",
    "Get a membership",
    "Get a subscription",
    "Get a subscription box",
    "Finally finish that project",
    "Finally finish that book",
    "Finally finish that game",
    "Finally finish that puzzle",
    "Finally finish that movie",
    "Finally finish that show",
    "Finally finish that series",
    "Finally finish that season",
    "Find a new job",
    "Find a new hobby",
    "Find a new passion",
    "Find a new interest",
    "Find a new friend",
    "Find a new partner",
    "Find a new mentor",
    "Find a new teacher",
    "Find a new student",
    "Find a new client",
    "Find a new customer",
    "Find a new audience",
    "Find a new market",
    "Find a new niche",
    "Find a new opportunity",
    "Find a new challenge",
    "Find a new goal",
    "Find a new purpose",
    "Find a new mission",
    "Find a new vision",
    "Find a new dream",
    "Find a new wish",
    "Find a new hope",
    "Find a new desire",
    "Find a new fantasy",
    "Break a bad habit",
    "Break a bad addiction",
    "Break a bad cycle",
    "Break a bad pattern",
    "Break a bad routine",
    "Break a bad tradition",
    "Break a bad rule",
    "Break a bad law",
    "Break a bad record",
    "Break a bad streak",
    "Break up with someone",
    "Break out of something",
    "Break through something",
    "Break into something",
    "Eat healthier",
    "Exercise more",
    "Sleep better",
    "Work smarter",
    "Play harder",
    "Learn faster",
    "Grow stronger",
    "Live longer",
    "Love deeper",
    "Laugh louder",
    "Cry harder",
    "Think clearer",
    "Feel better",
    "Be happier",
    "Do more",
    "Have more",
    "Be more",
    "Make more",
    "Take more",
    "Give more",
    "Get more",
    "See more",
    "Hear more",
    "Taste more",
    "Smell more",
    "Touch more",
    "Experience more",
    "Enjoy more",
    "Appreciate more",
    "Understand more",
    "Learn more",
    "Know more",
    "Do less",
    "Have less",
    "Be less",
    "Make less",
    "Take less",
    "Give less",
    "Get less",
    "Impress someone",
    "Inspire someone",
    "Motivate someone",
    "Encourage someone",
    "Support someone",
    "Help someone",
    "Teach someone",
    "Guide someone",
    "Lead someone",
    "Follow someone",
    "Improve something",
    "Fix something",
    "Repair something",
    "Replace something",
    "Renew something",
    "Convince someone to marry me",
    "Convince someone to date me",
    "Convince someone to hire me",
    "Convince someone to promote me",
    "Convince someone to invest in me",
    "Convince someone to believe in me",
    "Learn to drive",
    "Learn to ride a bike",
    "Learn to ride a motorcycle",
    "Learn to ride a horse",
    "Tell someone I love them",
    "Tell someone I miss them",
    "Tell someone I need them",
    "Tell someone I want them",
    "Make someone happy",
    "Make someone smile",
    "Make someone laugh",
    "Make someone cry",
    "Make someone proud",
    "Make someone jealous",
    "Make someone angry",
    "Make someone sad",
    "Make someone feel loved",
    "Make someone feel special",
    "Make someone feel important",
    "Make someone feel appreciated",
    "Make someone feel respected",
    "Make someone feel understood",
    "Make someone feel accepted",
    "Get better at my job",
    "Get better at my hobby",
    "Get better at my passion",
    "Get better at my interest",
    "Get better at my skill",
    "Get better at my talent",
    "Get better at my craft",
    "Get better at my art",
    "Give better feedback",
    "Give better advice",
    "Give better support",
    "Give better guidance",
    "Give better direction",
    "Give better instruction",
    "Give better leadership",
    "Give better management",
]

with open("/home/darf3/llm_game/longterm_goal_list.txt", "w") as file:
    for goal in longterm_goals:
        file.write(goal + "\n")
